version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: DB
    build:
      context: .
      dockerfile: docker/mySQL/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root-pass
      MYSQL_DATABASE: practice
      MYSQL_USER: user
      MYSQL_PASSWORD: user-pass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql-data: